/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package billingcp;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.LinkedList;
import java.util.Queue;
import javax.swing.JOptionPane;
/**
 *
 * @author Sumer
 */
public class frame2 extends javax.swing.JFrame {
    
   
    Queue<String> name=new LinkedList<>();
    Queue<String> qnt=new LinkedList<>();
    Queue<Double> kg=new LinkedList<>();
    Queue<Double> rate=new LinkedList<>();
      
    public frame2() {
        initComponents();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/biling","root","root");

            Statement stmt=con.createStatement();
            String querry="Select * from items";
            ResultSet rs=stmt.executeQuery(querry);
            
            while(rs.next()){
                
                String str=rs.getString("product");
                cb1.addItem(str);                
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        T2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        T15 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        T11 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        T12 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        T13 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        T14 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        T41 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        cb1 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        T48 = new javax.swing.JTextField();
        T42 = new javax.swing.JTextField();
        T43 = new javax.swing.JTextField();
        T44 = new javax.swing.JTextField();
        T45 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton5.setText("NEXT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(1130, 690, 180, 70);

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("HSN/ACS code           --");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 50, 210, 50);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Check");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(640, 50, 110, 50);
        jPanel1.add(T2);
        T2.setBounds(350, 60, 140, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1270, 150);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);
        jPanel2.add(T15);
        T15.setBounds(260, 110, 200, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("ADD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(1140, 110, 70, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("NAME");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(140, 50, 90, 20);
        jPanel2.add(T11);
        T11.setBounds(80, 110, 150, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("ADDRESS");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(320, 50, 90, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("GSTIN");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(530, 50, 90, 20);
        jPanel2.add(T12);
        T12.setBounds(490, 110, 130, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("STATE");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(700, 50, 90, 20);

        T13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T13ActionPerformed(evt);
            }
        });
        jPanel2.add(T13);
        T13.setBounds(680, 110, 120, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("STATE CODE");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(840, 50, 90, 20);

        T14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T14ActionPerformed(evt);
            }
        });
        jPanel2.add(T14);
        T14.setBounds(840, 110, 120, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 150, 1270, 230);

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("IF NOT PRESENT");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(100, 610, 170, 40);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("IF NOT PRESENT");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(0, 170, 570, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Enter New Item --");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(120, 230, 130, 50);

        T41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T41ActionPerformed(evt);
            }
        });
        jPanel3.add(T41);
        T41.setBounds(300, 250, 150, 22);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("ADD");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(220, 320, 100, 40);

        jPanel3.add(cb1);
        cb1.setBounds(60, 70, 240, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Retrieve");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jButton4.setBounds(400, 70, 100, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 380, 580, 420);

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(null);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("ADD IN BILL");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6);
        jButton6.setBounds(170, 340, 170, 60);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("DATE");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(90, 50, 150, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("ITEM NAME");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(90, 100, 150, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("QUANTITY(bundles)");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(90, 150, 150, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("NET QUANTITY(kg)");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(90, 200, 150, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("RATE");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(90, 260, 150, 40);
        jPanel4.add(T48);
        T48.setBounds(290, 60, 150, 30);
        jPanel4.add(T42);
        T42.setBounds(290, 110, 150, 30);
        jPanel4.add(T43);
        T43.setBounds(290, 160, 150, 30);
        jPanel4.add(T44);
        T44.setBounds(290, 210, 150, 30);
        jPanel4.add(T45);
        T45.setBounds(290, 260, 150, 30);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(580, 380, 470, 420);

        jPanel5.setBackground(new java.awt.Color(255, 51, 51));
        jPanel5.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("FOR REPORT");
        jPanel5.add(jLabel15);
        jLabel15.setBounds(0, 30, 230, 80);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("GO");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton7);
        jButton7.setBounds(60, 130, 110, 40);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(1100, 390, 230, 210);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        
        try{
          Class.forName("com.mysql.jdbc.Driver"); 
         Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/biling","root","root");
        int code=Integer.parseInt(T2.getText());
        Statement stmt=con.createStatement();
        String querry="Select * from customer;";
        ResultSet rs = stmt.executeQuery(querry);
      int id=0;
        boolean present=false;
      while(rs.next()){
          id  = rs.getInt("hsn");
         if(id==code){
             JOptionPane.showMessageDialog(null, "Customer exists.");              
             present =true;             
             break;        
           }
      }    
          if(!present){
             JOptionPane.showMessageDialog(null, "Not exist");
            }         
          rs.close();
          
      }
      catch(Exception se){          
          JOptionPane.showMessageDialog(null,se);         
      } 
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        int id=Integer.parseInt(T2.getText());
        String name=T11.getText();
        int gst=Integer.parseInt(T12.getText());
        String state=T13.getText();
        int sc=Integer.parseInt(T14.getText());
        String add=T15.getText();
       
        try{
           String querry="insert into customer values("+id+",'"+name+"',"+gst+",'"+state+"',"+sc+",'"+add+"');";
           Class.forName("com.mysql.jdbc.Driver"); 
         Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/biling","root","root");
           Statement stmt=con.createStatement();
           stmt.executeUpdate(querry);
           JOptionPane.showMessageDialog(null, "Row added successfully");
           con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }      
       
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void T13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T13ActionPerformed

    private void T14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T14ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        cb1.addItem(T41.getText());
        String st=T41.getText();

        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/biling","root","root");

            Statement stmt=con.createStatement();
            String querry="insert into items values('"+st+"');";
            stmt.executeUpdate(querry);

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        T42.setText((String)cb1.getSelectedItem());
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat ft = new SimpleDateFormat( "HH:mm dd/MM/yyyy");

        T48.setText(ft.format(cal.getTime()));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        int id=Integer.parseInt(T2.getText());
        frame3 ob=new frame3(id,name,qnt,kg,rate);
        ob.setVisible(true);
        dispose();
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        name.add(T42.getText());
        qnt.add(T43.getText());
        kg.add(Double.parseDouble(T44.getText()));
        rate.add(Double.parseDouble(T45.getText()));
        
        T42.setText("");
        T43.setText("");
        T44.setText("");
        T45.setText("");
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
        frameR ob=new frameR();
        ob.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void T41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T41ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
             
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField T11;
    private javax.swing.JTextField T12;
    private javax.swing.JTextField T13;
    private javax.swing.JTextField T14;
    private javax.swing.JTextField T15;
    private javax.swing.JTextField T2;
    private javax.swing.JTextField T41;
    private javax.swing.JTextField T42;
    private javax.swing.JTextField T43;
    private javax.swing.JTextField T44;
    private javax.swing.JTextField T45;
    private javax.swing.JTextField T48;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables

    private static class frame4 {

       

        
    }
}
